"""
这里是项目配置文件
Django settings for django_keshihua project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-(c)=wv&djdpk5@q-&3)w%$x#@mfzrlk$ke**2qcn^^mdgvlk0t"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition
# 应用添加
INSTALLED_APPS = [
    "apps.Data_Center.apps.DataCenterConfig",  # 数据中心
    "apps.web_fengmian.apps.WebFengmianConfig",  # 网页封面
    "apps.login.apps.LoginConfig",  # 登录界面应用添加
    "apps.Amoyjob.apps.AmoyjobConfig",  # 厦门十万条招聘数据可视化大屏
    "apps.index.apps.IndexConfig",  # 首页
    "apps.trmall_order_resport.apps.TrmallOrderResportConfig",  # 天猫销售数据可视化大屏
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'silk',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'silk.middleware.SilkyMiddleware'
]

ROOT_URLCONF = "django_keshihua.urls"

# html模板注册
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'apps', 'web_fengmian', 'mapp', 'templates'),  # 封面
                 os.path.join(BASE_DIR, 'apps', 'login', 'login_mapp', 'templates'),  # 登录
                 os.path.join(BASE_DIR, 'templates'),  # 项目主要父模板html
                 os.path.join(BASE_DIR, 'apps', 'Data_Center', 'datacentermapp', 'templates'),  # 数据中心应用hmtl
                 os.path.join(BASE_DIR, 'apps', 'Amoyjob', 'amoyjobmapp', 'templates'),  # 厦门招聘数据可视化模块
                 os.path.join(BASE_DIR, 'apps', 'trmall_order_resport', 'tanmaomapp', 'templates'),  # 天猫销售数据
                 ],  # 添加首页html文件
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "django_keshihua.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# 数据库配置
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": 'raw_data',
        "USER": 'root',
        "PASSWORD": 'qazwsx@123',
        "HOST": '127.0.0.1',
        "PORT": 3306,
        "CONN_MAX_AGE": 300,  # 设置连接的最大寿命为300秒，可根据实际情况调整
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
# 配置static文件
STATIC_URL = "static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'apps', 'web_fengmian', 'mapp', 'static'),  # 封面
    os.path.join(BASE_DIR, 'apps', 'login', 'login_mapp', 'static'),  # 登录
    os.path.join(BASE_DIR, 'apps', 'Data_Center', 'datacentermapp', 'static'),  # 数据中心
    os.path.join(BASE_DIR, 'static'),  # 父模板
    os.path.join(BASE_DIR, 'apps', 'Amoyjob', 'amoyjobmapp', 'static'),  # 厦门招聘数据
    os.path.join(BASE_DIR,'apps','trmall_order_resport','tanmaomapp','static')#天猫销售数据

]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

############# celery的配置信息######
# 1 Broker配置，使用Redis作为消息中间件
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/1'

# 3 序列化方案--》json
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# 结果序列化方案

CELERY_RESULT_SERIALIZER = 'json'

# 4 任务结果过期时间，秒

CELERY_TASK_RESULT_EXPIRES = 60 * 60 * 24

CELERYD_CONCURRENCY = 20  # 并发worker数
CELERYD_MAX_TASKS_PER_CHILD = 100  # 每个worker最多执行万100个任务就会被销

# 5 时区配置
CELERY_TIMEZONE = 'Asia/Shanghai'

CELERY_ENABLE_UTC = False

CELERY_WORKER_CONCURRENCY = 4  # 并发的worker数量

DJANGO_CELERY_BEAT_TZ_AWARE = False

CELERY_WORKER_MAX_TASKS_PER_CHILD = 5  # 每个worker最多执行的任务数, 可防止内存泄漏
CELERY_TASK_TIME_LIMIT = 15 * 60  # 任务超时时间

CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True#消除警告


###############################redis缓存配置￥##########################################


CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/2',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}
