# Generated by Django 4.1.7 on 2024-04-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Data_Center", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TmallOrderReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.IntegerField(blank=True, null=True, verbose_name="订单编号"),
                ),
                (
                    "total_amount",
                    models.FloatField(blank=True, null=True, verbose_name="总金额"),
                ),
                (
                    "buyer_actual_payment",
                    models.FloatField(blank=True, null=True, verbose_name="买家实际支付金额"),
                ),
                (
                    "shipping_address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="收货地址"
                    ),
                ),
                (
                    "order_created_time",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="订单创建时间"
                    ),
                ),
                (
                    "order_paid_time",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="订单付款时间"
                    ),
                ),
                (
                    "refund_amount",
                    models.FloatField(blank=True, null=True, verbose_name="退款金额"),
                ),
            ],
            options={
                "db_table": "tmall_order_report",
                "managed": False,
            },
        ),
    ]
