# Generated by Django 4.1.7 on 2024-04-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Data_Center", "0002_tmallorderreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sztcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_no", models.CharField(blank=True, max_length=255, null=True)),
                ("deal_date", models.CharField(blank=True, max_length=255, null=True)),
                ("deal_type", models.CharField(blank=True, max_length=255, null=True)),
                ("deal_money", models.CharField(blank=True, max_length=255, null=True)),
                ("deal_value", models.CharField(blank=True, max_length=255, null=True)),
                ("equ_no", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("station", models.CharField(blank=True, max_length=255, null=True)),
                ("car_no", models.CharField(blank=True, max_length=255, null=True)),
                ("conn_mark", models.CharField(blank=True, max_length=255, null=True)),
                ("close_date", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "SZTcard",
                "managed": False,
            },
        ),
    ]
