# Generated by Django 5.0.4 on 2024-05-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TmallOrderReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.IntegerField(
                        blank=True, db_column="订单编号", null=True, verbose_name="订单编号"
                    ),
                ),
                (
                    "total_amount",
                    models.FloatField(
                        blank=True, db_column="总金额", null=True, verbose_name="总金额"
                    ),
                ),
                (
                    "buyer_actual_payment",
                    models.FloatField(
                        blank=True,
                        db_column="买家实际支付金额",
                        null=True,
                        verbose_name="买家实际支付金额",
                    ),
                ),
                (
                    "shipping_address",
                    models.CharField(
                        blank=True,
                        db_column="收货地址",
                        max_length=255,
                        null=True,
                        verbose_name="收货地址",
                    ),
                ),
                (
                    "order_created_time",
                    models.CharField(
                        blank=True,
                        db_column="订单创建时间",
                        max_length=255,
                        null=True,
                        verbose_name="订单创建时间",
                    ),
                ),
                (
                    "order_paid_time",
                    models.CharField(
                        blank=True,
                        db_column="订单付款时间",
                        max_length=255,
                        null=True,
                        verbose_name="订单付款时间",
                    ),
                ),
                (
                    "refund_amount",
                    models.FloatField(
                        blank=True, db_column="退款金额", null=True, verbose_name="退款金额"
                    ),
                ),
            ],
            options={
                "db_table": "tmall_order_report",
                "managed": False,
            },
        ),
    ]
