# Generated by Django 4.1.7 on 2024-04-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Amoyjob",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        blank=True, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.CharField(blank=True, max_length=255, null=True)),
                ("num", models.CharField(blank=True, max_length=255, null=True)),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("job_type", models.CharField(blank=True, max_length=255, null=True)),
                ("jobage", models.CharField(blank=True, max_length=255, null=True)),
                ("lang", models.CharField(blank=True, max_length=255, null=True)),
                ("age", models.CharField(blank=True, max_length=255, null=True)),
                ("sex", models.CharField(blank=True, max_length=255, null=True)),
                ("education", models.CharField(blank=True, max_length=255, null=True)),
                ("workplace", models.CharField(blank=True, max_length=255, null=True)),
                ("worktime", models.CharField(blank=True, max_length=255, null=True)),
                ("salary", models.CharField(blank=True, max_length=255, null=True)),
                ("welfare", models.CharField(blank=True, max_length=255, null=True)),
                ("hr", models.TextField(blank=True, null=True)),
                ("phone", models.TextField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "company_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("industry", models.CharField(blank=True, max_length=255, null=True)),
                ("require", models.TextField(blank=True, null=True)),
                (
                    "worktime_day",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("worktime_week", models.TextField(blank=True, null=True)),
                ("skill", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "amoyjobmapp",
                "managed": False,
            },
        ),
    ]
