# Generated by Django 5.0.4 on 2024-04-26 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Amoyjob", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="amoyjob",
            table="Amoyjob",
        ),
    ]
