# Generated by Django 5.0.4 on 2024-04-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=150, unique=True, verbose_name="用户名"),
                ),
                ("password", models.CharField(max_length=128, verbose_name="密码")),
            ],
        ),
    ]
